[2022-12-03T05:27:29.467+0000] {processor.py:153} INFO - Started process (PID=479) to work on /opt/airflow/dags/dag_1.py
[2022-12-03T05:27:29.474+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_1.py for tasks to queue
[2022-12-03T05:27:29.476+0000] {logging_mixin.py:137} INFO - [2022-12-03T05:27:29.476+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_1.py
[2022-12-03T05:27:29.490+0000] {logging_mixin.py:137} INFO - [2022-12-03T05:27:29.484+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_1.py", line 12
    description='This is our first dag'
              ^
SyntaxError: invalid syntax
[2022-12-03T05:27:29.492+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_1.py
[2022-12-03T05:27:29.522+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_1.py took 0.059 seconds
[2022-12-03T05:27:34.607+0000] {processor.py:153} INFO - Started process (PID=484) to work on /opt/airflow/dags/dag_1.py
[2022-12-03T05:27:34.609+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_1.py for tasks to queue
[2022-12-03T05:27:34.614+0000] {logging_mixin.py:137} INFO - [2022-12-03T05:27:34.614+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_1.py
[2022-12-03T05:27:34.627+0000] {logging_mixin.py:137} INFO - [2022-12-03T05:27:34.626+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_1.py", line 12
    description='This is our first dag'
              ^
SyntaxError: invalid syntax
[2022-12-03T05:27:34.628+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_1.py
[2022-12-03T05:27:34.659+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_1.py took 0.056 seconds
[2022-12-03T05:27:59.042+0000] {processor.py:153} INFO - Started process (PID=513) to work on /opt/airflow/dags/dag_1.py
[2022-12-03T05:27:59.044+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_1.py for tasks to queue
[2022-12-03T05:27:59.046+0000] {logging_mixin.py:137} INFO - [2022-12-03T05:27:59.046+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_1.py
[2022-12-03T05:27:59.061+0000] {logging_mixin.py:137} INFO - [2022-12-03T05:27:59.056+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_1.py", line 12
    default_args=default_args,
               ^
SyntaxError: invalid syntax
[2022-12-03T05:27:59.063+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_1.py
[2022-12-03T05:27:59.088+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_1.py took 0.051 seconds
[2022-12-03T05:28:17.303+0000] {processor.py:153} INFO - Started process (PID=541) to work on /opt/airflow/dags/dag_1.py
[2022-12-03T05:28:17.305+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_1.py for tasks to queue
[2022-12-03T05:28:17.306+0000] {logging_mixin.py:137} INFO - [2022-12-03T05:28:17.306+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_1.py
[2022-12-03T05:28:17.313+0000] {logging_mixin.py:137} INFO - [2022-12-03T05:28:17.312+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_1.py", line 13
    default_args=default_args,
               ^
SyntaxError: invalid syntax
[2022-12-03T05:28:17.314+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_1.py
[2022-12-03T05:28:17.335+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_1.py took 0.035 seconds
[2022-12-03T05:28:41.708+0000] {processor.py:153} INFO - Started process (PID=570) to work on /opt/airflow/dags/dag_1.py
[2022-12-03T05:28:41.711+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_1.py for tasks to queue
[2022-12-03T05:28:41.713+0000] {logging_mixin.py:137} INFO - [2022-12-03T05:28:41.713+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_1.py
[2022-12-03T05:28:41.732+0000] {logging_mixin.py:137} INFO - [2022-12-03T05:28:41.730+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_1.py", line 1
    from apache-airflow import DAG
               ^
SyntaxError: invalid syntax
[2022-12-03T05:28:41.734+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_1.py
[2022-12-03T05:28:41.753+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_1.py took 0.050 seconds
[2022-12-03T05:28:46.822+0000] {processor.py:153} INFO - Started process (PID=575) to work on /opt/airflow/dags/dag_1.py
[2022-12-03T05:28:46.829+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_1.py for tasks to queue
[2022-12-03T05:28:46.834+0000] {logging_mixin.py:137} INFO - [2022-12-03T05:28:46.833+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_1.py
[2022-12-03T05:28:46.963+0000] {logging_mixin.py:137} INFO - [2022-12-03T05:28:46.955+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_1.py", line 13
    default_args=default_args,
               ^
SyntaxError: invalid syntax
[2022-12-03T05:28:46.967+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_1.py
[2022-12-03T05:28:47.055+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_1.py took 0.238 seconds
[2022-12-03T05:29:17.210+0000] {processor.py:153} INFO - Started process (PID=615) to work on /opt/airflow/dags/dag_1.py
[2022-12-03T05:29:17.212+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_1.py for tasks to queue
[2022-12-03T05:29:17.214+0000] {logging_mixin.py:137} INFO - [2022-12-03T05:29:17.214+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_1.py
[2022-12-03T05:29:17.220+0000] {logging_mixin.py:137} INFO - [2022-12-03T05:29:17.219+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_1.py", line 13
    default_args=default_args,
               ^
SyntaxError: invalid syntax
[2022-12-03T05:29:17.221+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_1.py
[2022-12-03T05:29:17.243+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_1.py took 0.037 seconds
[2022-12-03T05:29:47.633+0000] {processor.py:153} INFO - Started process (PID=644) to work on /opt/airflow/dags/dag_1.py
[2022-12-03T05:29:47.635+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_1.py for tasks to queue
[2022-12-03T05:29:47.637+0000] {logging_mixin.py:137} INFO - [2022-12-03T05:29:47.637+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_1.py
[2022-12-03T05:29:47.648+0000] {logging_mixin.py:137} INFO - [2022-12-03T05:29:47.647+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_1.py", line 13
    default_args=default_args,
               ^
SyntaxError: invalid syntax
[2022-12-03T05:29:47.650+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_1.py
[2022-12-03T05:29:47.685+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_1.py took 0.055 seconds
[2022-12-03T05:30:18.101+0000] {processor.py:153} INFO - Started process (PID=685) to work on /opt/airflow/dags/dag_1.py
[2022-12-03T05:30:18.103+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_1.py for tasks to queue
[2022-12-03T05:30:18.105+0000] {logging_mixin.py:137} INFO - [2022-12-03T05:30:18.104+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_1.py
[2022-12-03T05:30:18.112+0000] {logging_mixin.py:137} INFO - [2022-12-03T05:30:18.111+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_1.py", line 13
    default_args=default_args,
               ^
SyntaxError: invalid syntax
[2022-12-03T05:30:18.114+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_1.py
[2022-12-03T05:30:18.139+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_1.py took 0.041 seconds
[2022-12-03T05:30:24.208+0000] {processor.py:153} INFO - Started process (PID=690) to work on /opt/airflow/dags/dag_1.py
[2022-12-03T05:30:24.210+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_1.py for tasks to queue
[2022-12-03T05:30:24.211+0000] {logging_mixin.py:137} INFO - [2022-12-03T05:30:24.211+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_1.py
[2022-12-03T05:30:24.221+0000] {logging_mixin.py:137} INFO - [2022-12-03T05:30:24.220+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_1.py", line 12
    default_args=default_args,
               ^
SyntaxError: invalid syntax
[2022-12-03T05:30:24.223+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_1.py
[2022-12-03T05:30:24.247+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_1.py took 0.042 seconds
[2022-12-03T05:30:25.288+0000] {processor.py:153} INFO - Started process (PID=695) to work on /opt/airflow/dags/dag_1.py
[2022-12-03T05:30:25.290+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_1.py for tasks to queue
[2022-12-03T05:30:25.291+0000] {logging_mixin.py:137} INFO - [2022-12-03T05:30:25.291+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_1.py
[2022-12-03T05:30:25.296+0000] {logging_mixin.py:137} INFO - [2022-12-03T05:30:25.296+0000] {dagbag.py:320} INFO - File /opt/airflow/dags/dag_1.py assumed to contain no DAGs. Skipping.
[2022-12-03T05:30:25.297+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_1.py
[2022-12-03T05:30:25.310+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_1.py took 0.025 seconds
[2022-12-03T05:30:31.404+0000] {processor.py:153} INFO - Started process (PID=712) to work on /opt/airflow/dags/dag_1.py
[2022-12-03T05:30:31.406+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_1.py for tasks to queue
[2022-12-03T05:30:31.410+0000] {logging_mixin.py:137} INFO - [2022-12-03T05:30:31.410+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_1.py
[2022-12-03T05:30:31.422+0000] {logging_mixin.py:137} INFO - [2022-12-03T05:30:31.421+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_1.py", line 12
    default_args=default_args,
               ^
SyntaxError: invalid syntax
[2022-12-03T05:30:31.424+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_1.py
[2022-12-03T05:30:31.457+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_1.py took 0.057 seconds
[2022-12-03T05:31:01.830+0000] {processor.py:153} INFO - Started process (PID=742) to work on /opt/airflow/dags/dag_1.py
[2022-12-03T05:31:01.834+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_1.py for tasks to queue
[2022-12-03T05:31:01.838+0000] {logging_mixin.py:137} INFO - [2022-12-03T05:31:01.838+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_1.py
[2022-12-03T05:31:01.860+0000] {logging_mixin.py:137} INFO - [2022-12-03T05:31:01.851+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_1.py", line 12
    default_args=default_args,
               ^
SyntaxError: invalid syntax
[2022-12-03T05:31:01.864+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_1.py
[2022-12-03T05:31:01.906+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_1.py took 0.081 seconds
[2022-12-03T05:31:32.337+0000] {processor.py:153} INFO - Started process (PID=784) to work on /opt/airflow/dags/dag_1.py
[2022-12-03T05:31:32.340+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_1.py for tasks to queue
[2022-12-03T05:31:32.342+0000] {logging_mixin.py:137} INFO - [2022-12-03T05:31:32.342+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_1.py
[2022-12-03T05:31:32.359+0000] {logging_mixin.py:137} INFO - [2022-12-03T05:31:32.357+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_1.py", line 12
    default_args=default_args,
               ^
SyntaxError: invalid syntax
[2022-12-03T05:31:32.361+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_1.py
[2022-12-03T05:31:32.393+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_1.py took 0.059 seconds
[2022-12-03T05:32:02.874+0000] {processor.py:153} INFO - Started process (PID=813) to work on /opt/airflow/dags/dag_1.py
[2022-12-03T05:32:02.879+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_1.py for tasks to queue
[2022-12-03T05:32:02.881+0000] {logging_mixin.py:137} INFO - [2022-12-03T05:32:02.881+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_1.py
[2022-12-03T05:32:02.891+0000] {logging_mixin.py:137} INFO - [2022-12-03T05:32:02.889+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_1.py", line 12
    default_args=default_args,
               ^
SyntaxError: invalid syntax
[2022-12-03T05:32:02.892+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_1.py
[2022-12-03T05:32:02.917+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_1.py took 0.047 seconds
[2022-12-03T05:32:33.314+0000] {processor.py:153} INFO - Started process (PID=854) to work on /opt/airflow/dags/dag_1.py
[2022-12-03T05:32:33.317+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_1.py for tasks to queue
[2022-12-03T05:32:33.320+0000] {logging_mixin.py:137} INFO - [2022-12-03T05:32:33.319+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_1.py
[2022-12-03T05:32:33.334+0000] {logging_mixin.py:137} INFO - [2022-12-03T05:32:33.332+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_1.py", line 12
    default_args=default_args,
               ^
SyntaxError: invalid syntax
[2022-12-03T05:32:33.335+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_1.py
[2022-12-03T05:32:33.354+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_1.py took 0.044 seconds
[2022-12-03T05:33:03.791+0000] {processor.py:153} INFO - Started process (PID=896) to work on /opt/airflow/dags/dag_1.py
[2022-12-03T05:33:03.797+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_1.py for tasks to queue
[2022-12-03T05:33:03.799+0000] {logging_mixin.py:137} INFO - [2022-12-03T05:33:03.799+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_1.py
[2022-12-03T05:33:03.814+0000] {logging_mixin.py:137} INFO - [2022-12-03T05:33:03.811+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_1.py", line 12
    default_args=default_args,
               ^
SyntaxError: invalid syntax
[2022-12-03T05:33:03.815+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_1.py
[2022-12-03T05:33:03.858+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_1.py took 0.077 seconds
[2022-12-03T05:33:34.315+0000] {processor.py:153} INFO - Started process (PID=926) to work on /opt/airflow/dags/dag_1.py
[2022-12-03T05:33:34.318+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_1.py for tasks to queue
[2022-12-03T05:33:34.319+0000] {logging_mixin.py:137} INFO - [2022-12-03T05:33:34.319+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_1.py
[2022-12-03T05:33:34.330+0000] {logging_mixin.py:137} INFO - [2022-12-03T05:33:34.328+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_1.py", line 12
    default_args=default_args,
               ^
SyntaxError: invalid syntax
[2022-12-03T05:33:34.331+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_1.py
[2022-12-03T05:33:34.355+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_1.py took 0.044 seconds
[2022-12-03T05:34:04.673+0000] {processor.py:153} INFO - Started process (PID=967) to work on /opt/airflow/dags/dag_1.py
[2022-12-03T05:34:04.674+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_1.py for tasks to queue
[2022-12-03T05:34:04.676+0000] {logging_mixin.py:137} INFO - [2022-12-03T05:34:04.675+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_1.py
[2022-12-03T05:34:04.689+0000] {logging_mixin.py:137} INFO - [2022-12-03T05:34:04.687+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_1.py", line 12
    default_args=default_args,
               ^
SyntaxError: invalid syntax
[2022-12-03T05:34:04.691+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_1.py
[2022-12-03T05:34:04.708+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_1.py took 0.038 seconds
[2022-12-03T05:34:35.086+0000] {processor.py:153} INFO - Started process (PID=996) to work on /opt/airflow/dags/dag_1.py
[2022-12-03T05:34:35.090+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_1.py for tasks to queue
[2022-12-03T05:34:35.091+0000] {logging_mixin.py:137} INFO - [2022-12-03T05:34:35.091+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_1.py
[2022-12-03T05:34:35.099+0000] {logging_mixin.py:137} INFO - [2022-12-03T05:34:35.098+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_1.py", line 12
    default_args=default_args,
               ^
SyntaxError: invalid syntax
[2022-12-03T05:34:35.100+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_1.py
[2022-12-03T05:34:35.123+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_1.py took 0.043 seconds
[2022-12-03T05:35:05.586+0000] {processor.py:153} INFO - Started process (PID=1038) to work on /opt/airflow/dags/dag_1.py
[2022-12-03T05:35:05.589+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_1.py for tasks to queue
[2022-12-03T05:35:05.592+0000] {logging_mixin.py:137} INFO - [2022-12-03T05:35:05.591+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_1.py
[2022-12-03T05:35:05.603+0000] {logging_mixin.py:137} INFO - [2022-12-03T05:35:05.599+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_1.py", line 12
    default_args=default_args,
               ^
SyntaxError: invalid syntax
[2022-12-03T05:35:05.606+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_1.py
[2022-12-03T05:35:05.626+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_1.py took 0.044 seconds
[2022-12-03T05:35:36.163+0000] {processor.py:153} INFO - Started process (PID=1067) to work on /opt/airflow/dags/dag_1.py
[2022-12-03T05:35:36.165+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_1.py for tasks to queue
[2022-12-03T05:35:36.166+0000] {logging_mixin.py:137} INFO - [2022-12-03T05:35:36.166+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_1.py
[2022-12-03T05:35:36.178+0000] {logging_mixin.py:137} INFO - [2022-12-03T05:35:36.176+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_1.py", line 12
    default_args=default_args,
               ^
SyntaxError: invalid syntax
[2022-12-03T05:35:36.179+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_1.py
[2022-12-03T05:35:36.209+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_1.py took 0.049 seconds
[2022-12-03T05:35:43.320+0000] {processor.py:153} INFO - Started process (PID=1085) to work on /opt/airflow/dags/dag_1.py
[2022-12-03T05:35:43.323+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_1.py for tasks to queue
[2022-12-03T05:35:43.324+0000] {logging_mixin.py:137} INFO - [2022-12-03T05:35:43.324+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_1.py
[2022-12-03T05:35:43.332+0000] {logging_mixin.py:137} INFO - [2022-12-03T05:35:43.331+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_1.py", line 12
    default_args= default_args,
               ^
SyntaxError: invalid syntax
[2022-12-03T05:35:43.333+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_1.py
[2022-12-03T05:35:43.354+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_1.py took 0.040 seconds
[2022-12-03T05:35:44.452+0000] {processor.py:153} INFO - Started process (PID=1090) to work on /opt/airflow/dags/dag_1.py
[2022-12-03T05:35:44.455+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_1.py for tasks to queue
[2022-12-03T05:35:44.457+0000] {logging_mixin.py:137} INFO - [2022-12-03T05:35:44.457+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_1.py
[2022-12-03T05:35:44.470+0000] {logging_mixin.py:137} INFO - [2022-12-03T05:35:44.469+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_1.py", line 12
    default_args=default_args,
               ^
SyntaxError: invalid syntax
[2022-12-03T05:35:44.472+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_1.py
[2022-12-03T05:35:44.492+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_1.py took 0.044 seconds
[2022-12-03T05:36:14.891+0000] {processor.py:153} INFO - Started process (PID=1131) to work on /opt/airflow/dags/dag_1.py
[2022-12-03T05:36:14.894+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_1.py for tasks to queue
[2022-12-03T05:36:14.896+0000] {logging_mixin.py:137} INFO - [2022-12-03T05:36:14.896+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_1.py
[2022-12-03T05:36:14.906+0000] {logging_mixin.py:137} INFO - [2022-12-03T05:36:14.905+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dag_1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_1.py", line 12
    default_args=default_args,
               ^
SyntaxError: invalid syntax
[2022-12-03T05:36:14.908+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_1.py
[2022-12-03T05:36:14.927+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_1.py took 0.039 seconds
